version: 1.0.0.{build}
assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"


language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.5
before_script:
  - dotnet restore
script:  
  - dotnet test ./UnitTestCore -c Release -f netcoreapp2.0
